version: '3'
services:
  runner: &base
    image: plutino/mpt-server
    environment:
      - MONGODB_HOST=mongodb
    volumes:
      - ./server:/app
    depends_on:
      - mongodb
    command: "/bin/sh"

  dev-server:
    <<: *base
    command: 'yarn start'
    environment:
      - MONGODB_HOST=mongodb
      - NODE_ENV=development
    ports:
      - "${PORT:-3000}:3000"

  mongodb:
    image: "mvertes/alpine-mongo"
    volumes:
      - database:/data/db

volumes:
  database:
